# Base configuration for ALL ESPHome devices
# Universal services that work on any platform

logger:
  level: INFO
  logs:
    component: ERROR

api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 15min

ota:
  - platform: esphome
    password: !secret ota_password

safe_mode:

captive_portal:

mdns:
  disabled: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: LIGHT
  ap:
    password: !secret ap_password
    # SSID set per-device using ${friendly_name}

time:
  - platform: homeassistant
    id: homeassistant_time

interval:
  - interval: 5min
    then:
      - logger.log: "Device healthy"
