substitutions:
  device_name: esp32-cam-front-door
  friendly_name: "Front Door Camera"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

packages:
  base: !include ../../common/base.yaml
  platform: !include ../../common/esp32-platform.yaml
  diagnostics: !include ../../common/diagnostics.yaml
  hardware: !include ../../devices/ai-thinker/esp32-cam.yaml

wifi:
  ap:
    ssid: "${friendly_name} Fallback"
