substitutions:
  device_name: shelly-plus-1pm-heater
  friendly_name: "Space Heater"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

packages:
  base: !include ../../common/base.yaml
  platform: !include ../../common/esp32-platform.yaml
  diagnostics: !include ../../common/diagnostics.yaml
  web_server: !include ../../common/web-server.yaml
  hardware: !include ../../devices/shelly/plus-1pm.yaml

wifi:
  ap:
    ssid: "${friendly_name} Fallback"
