substitutions:
  device_name: sonoff-mini-r4-closet
  friendly_name: "Closet Light"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

packages:
  base: !include ../../common/base.yaml
  platform: !include ../../common/esp32-platform.yaml
  diagnostics: !include ../../common/diagnostics.yaml
  web_server: !include ../../common/web-server.yaml
  hardware: !include ../../devices/sonoff/mini-r4.yaml

wifi:
  ap:
    ssid: "${friendly_name} Fallback"
