# Wyze Outdoor Plug hardware definition
# Board type specified here since all Wyze plugs use esp32dev

esp32:
  board: esp32dev  # Wyze uses original ESP32

substitutions:
  current_res: "0.001"
  voltage_div: "770"

sensor:
  - platform: adc
    pin: GPIO34
    name: "Light Sensor"
    id: lux_sensor
    update_interval: 10s
    attenuation: 12db
    entity_category: diagnostic
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5

  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: GPIO25
      inverted: true
    cf_pin: GPIO27
    cf1_pin: GPIO26
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    change_mode_every: 3
    update_interval: 3s

    current:
      name: "Current"
      id: current
      unit_of_measurement: A
      accuracy_decimals: 2
      device_class: current
      state_class: measurement
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 0.5 -> 0.5

    voltage:
      name: "Voltage"
      id: voltage
      unit_of_measurement: V
      accuracy_decimals: 1
      device_class: voltage
      state_class: measurement
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 120.0 -> 120.0

    power:
      name: "Power"
      id: power
      unit_of_measurement: W
      accuracy_decimals: 1
      device_class: power
      state_class: measurement
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 134 -> 58
        - lambda: |-
            if (x < 1.0) return 0.0;
            return x;

    energy:
      name: "Energy"
      id: energy
      unit_of_measurement: Wh
      accuracy_decimals: 2
      device_class: energy
      state_class: total_increasing
      filters:
        - multiply: 0.001

  - platform: total_daily_energy
    name: "Daily Energy"
    power_id: power
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO18
      mode: INPUT_PULLDOWN
      inverted: True
    name: "Button 1"
    id: button1
    entity_category: diagnostic
    internal: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - switch.toggle: relay1
    on_click:
      - min_length: 50ms
        max_length: 500ms
        then:
          - switch.toggle: relay1
      - min_length: 2s
        max_length: 5s
        then:
          - logger.log: "Button 1 long press detected"

  - platform: gpio
    pin:
      number: GPIO17
      mode: INPUT_PULLDOWN
      inverted: True
    name: "Button 2"
    id: button2
    entity_category: diagnostic
    internal: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - switch.toggle: relay2
    on_click:
      - min_length: 50ms
        max_length: 500ms
        then:
          - switch.toggle: relay2
      - min_length: 2s
        max_length: 5s
        then:
          - logger.log: "Button 2 long press detected"

  - platform: template
    name: "Daylight"
    id: daylight
    device_class: light
    lambda: |-
      if (id(lux_sensor).state > 2.0) {
        return true;
      } else {
        return false;
      }
    filters:
      - delayed_on: 30s
      - delayed_off: 30s

switch:
  - platform: gpio
    name: "Outlet 1"
    id: relay1
    pin:
      number: GPIO15
      inverted: false
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: relay1_led
    on_turn_off:
      - light.turn_off: relay1_led

  - platform: gpio
    name: "Outlet 2"
    id: relay2
    pin:
      number: GPIO32
      inverted: false
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: relay2_led
    on_turn_off:
      - light.turn_off: relay2_led

  - platform: restart
    name: "Restart"
    entity_category: diagnostic

  - platform: safe_mode
    name: "Safe Mode"
    entity_category: diagnostic

output:
  - platform: gpio
    pin: GPIO19
    inverted: true
    id: relay1_led_gpio
  - platform: gpio
    pin: GPIO16
    inverted: true
    id: relay2_led_gpio

light:
  - platform: binary
    name: "Outlet 1 LED"
    id: relay1_led
    internal: true
    output: relay1_led_gpio
  - platform: binary
    name: "Outlet 2 LED"
    id: relay2_led
    internal: true
    output: relay2_led_gpio

status_led:
  pin:
    number: GPIO5
    inverted: true
