name: Validate ESPHome Configs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - examples/local-development/wyzeoutdoor1.yaml
          - examples/local-development/wyzeoutdoor2.yaml
          - examples/local-development/wyzeoutdoor3.yaml
          - examples/local-development/sonoff-s31-kitchen.yaml
          - examples/local-development/sonoff-s31-garage-static-ip.yaml
          - examples/local-development/athom-pg01v3-eu-living-room.yaml
          - examples/local-development/airgradient-one-office.yaml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ESPHome
        run: pip install esphome

      - name: Create secrets.yaml
        run: |
          cat > secrets.yaml << EOF
          wifi_ssid: "test-network"
          wifi_password: "test-password"
          api_encryption_key: "rBPmvFdSW1At4ksEt3ut050Vcx6mVIeXBc46XNKF3Q8="
          ota_password: "test-ota-password"
          ap_password: "test-ap-password"
          wifi_gateway: "192.168.1.1"
          wifi_subnet: "255.255.255.0"
          EOF

      - name: Validate ${{ matrix.config }}
        run: esphome config ${{ matrix.config }}
