name: YAML Lint

on:
  push:
    branches: [main]
    paths:
      - "**.yaml"
      - "**.yml"
  pull_request:
    paths:
      - "**.yaml"
      - "**.yml"

jobs:
  yamllint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run yamllint
        run: yamllint --strict .
